### ISSUE TITLE
cuQuantum Appliance- 24.08-x86_64 provider tools problem

### ISSUE THREAD

**Issue by ssarikurt** [NVIDIA/cuQuantum#165]
Hi!

I encountered an issue using cusvaer as the backend while running the cuQuantum Appliance 24.08 (x86_64) in an Apptainer container.

I am attempting to run the cuquantum-benchmark suite with Qiskit as the frontend and cusvaer as the backend, as outlined below. The setup functions without error when using other backends, such as aer-cuda or aer-cusv.

Could you please assist me in resolving this issue?

apptainer run --nv cuquantum-appliance_24.08-x86_64 cuquantum-benchmarks circuit --frontend qiskit --backend cusvaer --nqubits 16 -v --ncputhreads 1 --cusvaer-global-index-bits 1 --cusvaer-p2p-device-bits 0

I got the below error:

INFO: nvidia devices detected
INFO: gpu functionality will be available

2024-11-08 11:16:45,136 DEBUG    ./data/qft.json not found
2024-11-08 11:16:45,364 DEBUG    Circuit loaded from circuits/qft_16_measure_v1.pickle
Traceback (most recent call last):
  File "/opt/conda/envs/cuquantum-24.08/bin/cuquantum-benchmarks", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/run.py", line 335, in run
    runner.run()
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/run_interface.py", line 92, in run
    self._run()
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/run_interface.py", line 270, in _run
    backend = createBackend(
              ^^^^^^^^^^^^^^
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/backends/__init__.py", line 34, in createBackend
    return backends[backend_name](ngpus, ncpu_threads, precision, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/backends/backend_qiskit.py", line 41, in __init__
    self.backend = self.create_aer_backend(self.identifier, ngpus, ncpu_threads, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cuquantum_benchmarks/backends/backend_qiskit.py", line 96, in create_aer_backend
    import cusvaer
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cusvaer/__init__.py", line 1, in <module>
    from . import backends
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cusvaer/backends/__init__.py", line 1, in <module>
    from .statevector_simulator import StatevectorSimulator
  File "/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/cusvaer/backends/statevector_simulator.py", line 62, in <module>
    from qiskit.providers.basic_provider.basic_provider_tools import cx_gate_matrix
ImportError: cannot import name 'cx_gate_matrix' from 'qiskit.providers.basic_provider.basic_provider_tools' (/opt/conda/envs/cuquantum-24.08/lib/python3.11/site-packages/qiskit/providers/basic_provider/basic_provider_tools.py)

**Comment by ymagchi** [comment]
Hi @ssarikurt,

Thank you for your inquiry.

Could you please confirm that the Qiskit version number is 1.0.2 in your environment?
cusvaer in cuQuantum Appliance 24.08 is expected to work with Qiskit 1.0.2, and it may not be compatible with newer versions.
